spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/forge_idea

spring.datasource.username=postgres
spring.datasource.password=postgres0212

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

